#define SPRITE_VRAM_BASE_ADDR 0x00000
#define SPRITE_SIZE 512 // 32x32 pixels, 4bpp
#define SPRITE_ATTR_BASE 0x1fc08
#define SPRITE_ATTR_ENTRY_SIZE 8

#define NUM_SPRITES 4

#define VERTICAL_SHIP_INDEX 0
#define HORIZONTAL_SHIP_INDEX 1

